version: '2'
services:
    database:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: webhooks
            POSTGRES_DB: webhooks
            POSTGRES_USER: webhooks
        ports:
            - "5432:5432"

    rabbit:
        image: dzubchik/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
    redis:
        image: redis
        ports:
            - "6379:6379"